// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryshjxguqwhlqhqievgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5c2hqeGd1cXdobHFocWlldmd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzEwMDksImV4cCI6MjA2MzE0NzAwOX0.ajtZ_VU-Hf7hgunUYc-rLxPJNkRgVx0rEN1SQsxUUhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);